# Generated by Django 5.0.6 on 2024-07-06 14:16

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=100)),
                ('forme', models.CharField(choices=[('comprime', 'Comprimé'), ('sirop', 'Sirop'), ('gelule', 'Gélule'), ('injection', 'Injection'), ('poudre', 'Poudre'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('creme', 'Crème'), ('onguent', 'Onguent'), ('suppositoire', 'Suppositoire'), ('ovule', 'Ovule'), ('patch_transdermique', 'Patch transdermique'), ('aerosol', 'Aérosol'), ('inhalateur', 'Inhalateur'), ('collyre', 'Collyre'), ('gouttes_auriculaires', 'Gouttes auriculaires'), ('gouttes_nasales', 'Gouttes nasales'), ('granules', 'Granules'), ('pastille', 'Pastille'), ('elixir', 'Elixir'), ('emulsion', 'Emulsion'), ('gel', 'Gel'), ('lozenge', 'Lozenge'), ('bain_de_bouche', 'Bain de bouche')], max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('posologie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masse', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='masse (kg)')),
                ('tension_systolique', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='Tension systolique (mmHg)')),
                ('tension_diastolique', models.IntegerField(validators=[django.core.validators.MinValueValidator(30)], verbose_name='Tension diastolique (mmHg)')),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(32)], verbose_name='Température (°C)')),
                ('pouls', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='Pouls (bpm)')),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('allergies_et_intolerance', models.TextField(blank=True, null=True)),
                ('fumeur', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('alcool', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.carnet')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='En attente', max_length=50)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('constantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.constantes')),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.consultation')),
                ('maladie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appFinal.maladie')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.specialite')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appFinal.medecin'),
        ),
        migrations.AddField(
            model_name='maladie',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.medicament'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(editable=False, max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.CharField(choices=[('Abobo', 'Abobo'), ('Aboisso', 'Aboisso'), ('Adjamé', 'Adjamé'), ('Adzopé', 'Adzopé'), ('Afféry', 'Afféry'), ('Agou', 'Agou'), ('Akoupé', 'Akoupé'), ('Alépé', 'Alépé'), ('Anyama', 'Anyama'), ('Arrah', 'Arrah'), ('Assinie', 'Assinie'), ('Attiégbé', 'Attiégbé'), ('Attécoubé', 'Attécoubé'), ('Badikaha', 'Badikaha'), ('Bangolo', 'Bangolo'), ('Biankouma', 'Biankouma'), ('Bingerville', 'Bingerville'), ('Bloléquin', 'Bloléquin'), ('Bodoukou', 'Bodoukou'), ('Bouaflé', 'Bouaflé'), ('Bouna', 'Bouna'), ('Boundiali', 'Boundiali'), ('Brignan', 'Brignan'), ('Broukro', 'Broukro'), ('Cocody', 'Cocody'), ('Dabakala', 'Dabakala'), ('Dimbokro', 'Dimbokro'), ('Divo', 'Divo'), ('Duékoué', 'Duékoué'), ('Ferkéssedougou', 'Ferkéssedougou'), ('Gagnoa', 'Gagnoa'), ('Guingré', 'Guingré'), ('Guéyo', 'Guéyo'), ('Issia', 'Issia'), ('Jacqueville', 'Jacqueville'), ('Jérenou', 'Jérenou'), ('Kani', 'Kani'), ('Katiola', 'Katiola'), ('Katié', 'Katié'), ('Kong', 'Kong'), ('Kouassi-Kouassikro', 'Kouassi-Kouassikro'), ('Kouibly', 'Kouibly'), ('Koumassi', 'Koumassi'), ('Kouto', 'Kouto'), ('Kpédékou', 'Kpédékou'), ('Kranou', 'Kranou'), ('Lakota', 'Lakota'), ('Man', 'Man'), ('Mankono', 'Mankono'), ('Marcory', 'Marcory'), ('Méagui', 'Méagui'), ('Mégué', 'Mégué'), ('Odienné', 'Odienné'), ('Oumé', 'Oumé'), ('Plateau', 'Plateau'), ('Port-Bouët', 'Port-Bouët'), ('Péhé', 'Péhé'), ('Raviart', 'Raviart'), ('Saboudougou', 'Saboudougou'), ('Sassandra', 'Sassandra'), ('Sikensi', 'Sikensi'), ('Sipilou', 'Sipilou'), ('Songon', 'Songon'), ('Soubré', 'Soubré'), ('Séguéla', 'Séguéla'), ('Séguélon', 'Séguélon'), ('Tabou', 'Tabou'), ('Tafiré', 'Tafiré'), ('Taï', 'Taï'), ('Tiassalé', 'Tiassalé'), ('Tiebissou', 'Tiebissou'), ('Tingrela', 'Tingrela'), ('Tiémé', 'Tiémé'), ('Touba', 'Touba'), ('Toumodi', 'Toumodi'), ('Treichville', 'Treichville'), ('Vavoua', 'Vavoua'), ('Yamoussoukro', 'Yamoussoukro'), ('Yopougon', 'Yopougon'), ('Zaranou', 'Zaranou'), ('Zatié', 'Zatié'), ('Zinguinéo', 'Zinguinéo'), ('yakassé-Attobrou', 'yakassé-Attobrou')], max_length=200)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A positif'), ('A-', 'A négatif'), ('B+', 'B positif'), ('B-', 'B négatif'), ('AB+', 'AB positif'), ('AB-', 'AB négatif'), ('O+', 'O positif'), ('O-', 'O négatif')], max_length=3)),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.infirmier')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.patient'),
        ),
        migrations.AddField(
            model_name='carnet',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appFinal.patient'),
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=datetime.date.today)),
                ('date_fin', models.DateField()),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.diagnostic')),
                ('medicaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.medicament')),
            ],
        ),
    ]
