# Generated by Django 5.0.6 on 2024-06-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('specialite', models.CharField(choices=[('cardiologue', 'Cardiologue'), ('dentiste', 'Dentiste'), ('dermatologue', 'Dermatologue'), ('gynécologue', 'Gynécologue'), ('généraliste', 'Généraliste'), ('neurologue', 'Neurologue'), ('ophtamologue', 'Ophtamologue'), ('psychiatre', 'Psychiatre'), ('psychologue', 'Psychologue'), ('pediatre', 'Pédiatre')], max_length=100)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.medecin'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(editable=False, max_length=6, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.infirmier')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.patient'),
        ),
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masse', models.FloatField(verbose_name='masse (kg)')),
                ('tension_arterielle', models.CharField(max_length=50, verbose_name='Tension artérielle (mmHg)')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Température (°C)')),
                ('pouls', models.IntegerField(verbose_name='Pouls (bpm)')),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('allergies_et_intolerance', models.TextField(blank=True, null=True)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A positif'), ('A-', 'A négatif'), ('B+', 'B positif'), ('B-', 'B négatif'), ('AB+', 'AB positif'), ('AB-', 'AB négatif'), ('O+', 'O positif'), ('O-', 'O négatif')], max_length=3)),
                ('fumeur', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('alcool', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appFinal.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinal.diagnostic')),
            ],
        ),
    ]
