# Generated by Django 5.0.6 on 2024-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='posologie',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(choices=[('Abobo', 'Abobo'), ('Aboisso', 'Aboisso'), ('Adjamé', 'Adjamé'), ('Adzopé', 'Adzopé'), ('Afféry', 'Afféry'), ('Agou', 'Agou'), ('Akoupé', 'Akoupé'), ('Alépé', 'Alépé'), ('Anyama', 'Anyama'), ('Arrah', 'Arrah'), ('Assinie', 'Assinie'), ('Attiégbé', 'Attiégbé'), ('Attécoubé', 'Attécoubé'), ('Badikaha', 'Badikaha'), ('Bangolo', 'Bangolo'), ('Biankouma', 'Biankouma'), ('Bingerville', 'Bingerville'), ('Bloléquin', 'Bloléquin'), ('Bodoukou', 'Bodoukou'), ('Bouaflé', 'Bouaflé'), ('Bouna', 'Bouna'), ('Boundiali', 'Boundiali'), ('Brignan', 'Brignan'), ('Broukro', 'Broukro'), ('Cocody', 'Cocody'), ('Dabakala', 'Dabakala'), ('Dimbokro', 'Dimbokro'), ('Divo', 'Divo'), ('Duékoué', 'Duékoué'), ('Ferkéssedougou', 'Ferkéssedougou'), ('Gagnoa', 'Gagnoa'), ('Guingré', 'Guingré'), ('Guéyo', 'Guéyo'), ('Issia', 'Issia'), ('Jacqueville', 'Jacqueville'), ('Jérenou', 'Jérenou'), ('Kani', 'Kani'), ('Katiola', 'Katiola'), ('Katié', 'Katié'), ('Kong', 'Kong'), ('Kouassi-Kouassikro', 'Kouassi-Kouassikro'), ('Kouibly', 'Kouibly'), ('Koumassi', 'Koumassi'), ('Kouto', 'Kouto'), ('Kpédékou', 'Kpédékou'), ('Kranou', 'Kranou'), ('Lakota', 'Lakota'), ('Man', 'Man'), ('Mankono', 'Mankono'), ('Marcory', 'Marcory'), ('Méagui', 'Méagui'), ('Mégué', 'Mégué'), ('Odienné', 'Odienné'), ('Oumé', 'Oumé'), ('Plateau', 'Plateau'), ('Port-Bouët', 'Port-Bouët'), ('Péhé', 'Péhé'), ('Raviart', 'Raviart'), ('Saboudougou', 'Saboudougou'), ('Sassandra', 'Sassandra'), ('Sikensi', 'Sikensi'), ('Sipilou', 'Sipilou'), ('Songon', 'Songon'), ('Soubré', 'Soubré'), ('Séguéla', 'Séguéla'), ('Séguélon', 'Séguélon'), ('Tabou', 'Tabou'), ('Tafiré', 'Tafiré'), ('Taï', 'Taï'), ('Tiassalé', 'Tiassalé'), ('Tiebissou', 'Tiebissou'), ('Tingrela', 'Tingrela'), ('Tiémé', 'Tiémé'), ('Touba', 'Touba'), ('Toumodi', 'Toumodi'), ('Treichville', 'Treichville'), ('Vavoua', 'Vavoua'), ('Yamoussoukro', 'Yamoussoukro'), ('Yopougon', 'Yopougon'), ('Zaranou', 'Zaranou'), ('Zatié', 'Zatié'), ('Zinguinéo', 'Zinguinéo'), ('yakassé-Attobrou', 'yakassé-Attobrou')], max_length=200),
        ),
    ]
