# Generated by Django 5.0.6 on 2024-06-25 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0002_traitement_posologie_alter_patient_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='masse',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='masse (kg)'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='pouls',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='Pouls (bpm)'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(32)], verbose_name='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='tension_arterielle',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tension artérielle (mmHg)'),
        ),
    ]
