# Generated by Django 5.0.6 on 2024-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0003_alter_carnet_masse_alter_carnet_pouls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='tension_arterielle',
            field=models.CharField(max_length=50, verbose_name='Tension artérielle (mmHg)'),
        ),
    ]
