# Generated by Django 5.0.6 on 2024-06-25 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0004_alter_carnet_tension_arterielle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='tension_arterielle',
        ),
        migrations.AddField(
            model_name='carnet',
            name='tension_diastolique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Tension diastolique (mmHg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carnet',
            name='tension_systolique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Tension systolique (mmHg)'),
            preserve_default=False,
        ),
    ]
