# Generated by Django 5.0.6 on 2024-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0005_remove_carnet_tension_arterielle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
